PUT {{url}}/cards/77687270-0ca3-427f-9620-38c97a281232
Authorization: Bearer {{token}}
Accept-Language: ru
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="title"

john_doe132
--MyBoundary
Content-Disposition: form-data; name="description"

haha hahaha hahaha hahaha hahaha hahaha ha
--MyBoundary
Content-Disposition: form-data; name="access_type"

public
--MyBoundary
Content-Disposition: form-data; name="file"; filename="document.png"
Content-Type: image/png

< ./../assets/screen.png
--MyBoundary--

###
