services:

  nginx:
    image: nginx:alpine
    tty: true
    ports:
      - "${PORT}:80"
    volumes:
      - './:/var/www'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    env_file:
      - .env
    links:
      - app
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/var/www'
      - './docker/app/www.conf:/usr/local/etc/php-fpm.d/www.conf'
    tty: true
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./../var/db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
    command: server /var/lib/minio/data --console-address ":9001"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - '${MINIO_PORT}:9001'
    volumes:
      - ${MINIO_PATH}:/var/lib/minio/data
    restart: unless-stopped
    networks:
      - app-network

  npm:
    image: node:24.12.0-alpine
    working_dir: /var/www/frontend
    entrypoint: [ "npm" ]
    volumes:
      - ./frontend:/var/www/frontend
      - ./public:/var/www/public

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
