### Добавление карточки в коллекцию
POST {{url}}/api/collections/d2edbc1a-fe79-4335-b983-3453cb0ed556/cards
Authorization: Bearer {{token}}
Accept-Language: ru
Content-Type: application/json

{
  "card_id": "a818c165-995e-4b4e-90a7-1b8194cbf2c8"
}