[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisor/supervisord.pid
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info

[program:notification-worker]
command=/bin/bash /var/www/docker/notification/worker.sh
process_name=%(program_name)s
numprocs=1
autostart=true
autorestart=true
startsecs=1
startretries=3
stdout_logfile=/var/log/web_push.log
stderr_logfile=/var/log/web_push.log
stdout_logfile_maxbytes=100MB
stderr_logfile_maxbytes=100MB
stdout_logfile_backups=2
stderr_logfile_backups=2
redirect_stderr=true
user=root