[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:notification-worker]
command=php /var/www/cli/cli.php notification send
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
startsecs=0
startretries=3
stdout_logfile=/var/log/web_push.log
stderr_logfile=/var/log/web_push.log
stdout_logfile_maxbytes=100MB
stderr_logfile_maxbytes=100MB